import type { Metadata } from 'next'
import { SEARCHABLE_ICON_COUNT } from '../../../data/library-catalog'

export type IntegrationSlug =
  | 'webflow-extension'
  | 'sketch-plugin'
  | 'powerpoint-addin'
  | 'google-slides-addon'
  | 'raycast-extension'
  | 'tailwind-plugin'
  | 'mcp-server'
  | 'jetbrains-plugin'
  | 'storybook-addon'
  | 'canva-app'
  | 'wordpress-plugin'
  | 'shopify-extension'
  | 'adobe-plugin'
  | 'obsidian-plugin'

export type IntegrationIcon =
  | 'layout'
  | 'presentation'
  | 'command'
  | 'wind'
  | 'radio'
  | 'blocks'
  | 'book'
  | 'image'
  | 'panel'
  | 'shop'
  | 'brush'
  | 'gem'

type IntegrationStatus = 'Package ready' | 'Local build' | 'Development preview' | 'Development build'

export type IntegrationConfig = {
  slug: IntegrationSlug
  name: string
  platform: string
  icon: IntegrationIcon
  mark: string
  status: IntegrationStatus
  statusTone: 'ready' | 'local' | 'development'
  eyebrow: string
  title: string
  description: string
  accent: string
  accentMuted: string
  previewContext: string
  previewAction: string
  outputLabel: string
  output: string
  account: string
  dragAndDrop: boolean
  styleControls?: boolean
  capabilities: string[]
  features: Array<{ title: string; text: string }>
  workflow: string[]
  requirements: string[]
  setup: string
  releaseTitle: string
  releaseText: string
}

export const integrationCatalog: Record<IntegrationSlug, IntegrationConfig> = {
  'webflow-extension': {
    slug: 'webflow-extension',
    name: 'Webflow Designer Extension',
    platform: 'Webflow',
    icon: 'layout',
    mark: 'WF',
    status: 'Development build',
    statusTone: 'development',
    eyebrow: 'DESIGNER-SIDE ICONS',
    title: 'Place styled SVG icons directly in Webflow Designer.',
    description: 'Search the live IconSearch catalog, adjust size and color, then add a reusable SVG asset before, inside, or after the selected canvas element.',
    accent: '#146ef5',
    accentMuted: 'rgba(20, 110, 245, 0.16)',
    previewContext: 'IconSearch - Webflow Designer',
    previewAction: 'Insert selected',
    outputLabel: 'Designer asset',
    output: 'lucide:house - SVG asset - 64 px - #111827',
    account: 'No IconSearch account',
    dragAndDrop: false,
    styleControls: true,
    capabilities: ['Designer API v2', 'Styled SVG asset reuse', 'Before, inside, or after placement'],
    features: [
      { title: 'Focused Designer panel', text: 'A compact two-column browser keeps previews, filters, styling, and insertion visible in Webflow\'s comfortable panel size.' },
      { title: 'Style before insertion', text: 'Set a precise pixel size, choose a custom color, or use a quick swatch before creating the SVG asset.' },
      { title: 'Native canvas placement', text: 'Insert an Image element before, inside, or after the selected Webflow element and keep the new icon selected.' },
      { title: 'Reusable site assets', text: 'Previously created color and size variants are reused locally instead of uploading duplicate SVG files.' },
    ],
    workflow: ['Open the extension in Webflow Designer', 'Select a canvas element', 'Search and style an icon', 'Choose placement and insert the SVG asset'],
    requirements: ['Node.js 22.13 or newer', 'A Webflow workspace with App development access', 'Design and asset-management capabilities on a test site'],
    setup: 'cd webflow-extension\nnpm install\nnpm run dev',
    releaseTitle: 'Ready for a Webflow Designer development test.',
    releaseText: 'The manifest, strict TypeScript build, safety checks, and bundle pass locally. App registration, an in-Designer capability test, listing assets, and Webflow Marketplace review remain before public availability.',
  },
  'sketch-plugin': {
    slug: 'sketch-plugin',
    name: 'Sketch Plugin',
    platform: 'Sketch',
    icon: 'gem',
    mark: 'SK',
    status: 'Package ready',
    statusTone: 'ready',
    eyebrow: 'EDITABLE CANVAS ICONS',
    title: 'Place editable SVG icons directly into Sketch documents.',
    description: 'Search across the live IconSearch catalog, refine by library and style, set color, size, and selection-relative placement, then insert a native editable SVG group.',
    accent: '#f4b400',
    accentMuted: 'rgba(244, 180, 0, 0.16)',
    previewContext: 'IconSearch - Sketch plugin window',
    previewAction: 'Insert editable SVG',
    outputLabel: 'Sketch layer',
    output: 'lucide:house - SVG group - 64 px - #2563EB',
    account: 'No IconSearch account',
    dragAndDrop: false,
    styleControls: true,
    capabilities: ['Native editable SVG groups', 'Selection-aware placement', 'Local recent icons'],
    features: [
      { title: 'Fast visual browsing', text: 'A compact three-column plugin window keeps mixed-library results, filters, selected preview, and styling controls visible without crowding the canvas.' },
      { title: 'Editable native output', text: 'Sanitized SVG is imported through Sketch\'s supported JavaScript API as an editable group rather than a flattened bitmap.' },
      { title: 'Predictable placement', text: 'Insert beside the current selection, centered over it, or at the page origin, then keep the new layer selected and visible.' },
      { title: 'Small security surface', text: 'The plugin uses the public icon API, embeds no credentials, validates SVG in both runtime contexts, and stores recents only in the local webview.' },
    ],
    workflow: ['Build the three-file .sketchplugin bundle', 'Install it on a macOS device with Sketch', 'Search and style an icon in the plugin window', 'Insert the editable SVG relative to the current selection'],
    requirements: ['Node.js 22.13 or newer for development', 'A macOS device with a supported Sketch installation', 'A test Sketch document for native host validation'],
    setup: 'cd sketch-plugin\nnpm install\nnpm run verify\nopen dist/IconSearch.sketchplugin',
    releaseTitle: 'Packaged for native Sketch host testing.',
    releaseText: 'The webview, dual SVG validation, native insertion command, tests, dependency audit, .sketchplugin bundle, and exact three-file release ZIP pass locally. A real Sketch host test, hosted updating JSON, release assets, and official plugin-directory submission remain before public availability.',
  },
  'powerpoint-addin': {
    slug: 'powerpoint-addin',
    name: 'PowerPoint Add-in',
    platform: 'Microsoft PowerPoint',
    icon: 'presentation',
    mark: 'PP',
    status: 'Development build',
    statusTone: 'development',
    eyebrow: 'SLIDE-SIDE ICON SEARCH',
    title: 'Insert presentation-ready icons without leaving PowerPoint.',
    description: 'Search the live IconSearch catalog, adjust size, color, and placement, then insert a sanitized SVG or transparent PNG fallback onto the current slide.',
    accent: '#d24726',
    accentMuted: 'rgba(210, 71, 38, 0.15)',
    previewContext: 'IconSearch - PowerPoint task pane',
    previewAction: 'Insert into slide',
    outputLabel: 'Slide asset',
    output: 'lucide:house - SVG - 72 pt - #D24726',
    account: 'No IconSearch account',
    dragAndDrop: false,
    styleControls: true,
    capabilities: ['PowerPoint task pane', 'SVG with PNG fallback', 'Size, color, and placement'],
    features: [
      { title: 'Fast mixed-library search', text: 'Results begin with a useful cross-library query and hydrate visible SVG previews progressively for smooth task-pane scrolling.' },
      { title: 'Slide-ready styling', text: 'Choose a point size, exact hex color, quick swatch, and supported placement before inserting the icon.' },
      { title: 'Broad host compatibility', text: 'Modern PowerPoint hosts receive sanitized SVG while older supported hosts receive a high-quality transparent PNG.' },
      { title: 'Minimal data access', text: 'The add-in uses the public icon API, embeds no secret keys, and requests only the document permission required for insertion.' },
    ],
    workflow: ['Install dependencies and trust the local HTTPS certificate', 'Start and sideload the XML manifest in PowerPoint', 'Search and style an icon in the task pane', 'Insert the selected icon onto the current slide'],
    requirements: ['Node.js 22.13 or newer', 'PowerPoint desktop or web with add-in sideloading enabled', 'A Microsoft 365 account for local host testing'],
    setup: 'cd powerpoint-addin\nnpm install\nnpx office-addin-dev-certs install\nnpm start',
    releaseTitle: 'Ready for local PowerPoint sideloading and host tests.',
    releaseText: 'The task pane, sanitizer, SVG and PNG insertion paths, HTTPS tooling, and add-in-only XML manifest are implemented. Production hosting, cross-host QA, listing assets, and Microsoft Marketplace review remain before public availability.',
  },
  'google-slides-addon': {
    slug: 'google-slides-addon',
    name: 'Google Slides Add-on',
    platform: 'Google Slides',
    icon: 'presentation',
    mark: 'GS',
    status: 'Development build',
    statusTone: 'development',
    eyebrow: 'SLIDE-SIDE ICON SEARCH',
    title: 'Insert polished icons directly into Google Slides.',
    description: 'Search across the live IconSearch catalog, refine by library and style, set color, point size, and placement, then insert a transparent PNG onto the current slide.',
    accent: '#f9ab00',
    accentMuted: 'rgba(249, 171, 0, 0.16)',
    previewContext: 'IconSearch - Google Slides sidebar',
    previewAction: 'Insert into slide',
    outputLabel: 'Slide asset',
    output: 'lucide:house - PNG - 72 pt - #2563EB',
    account: 'No IconSearch account',
    dragAndDrop: false,
    styleControls: true,
    capabilities: ['Editor add-on sidebar', 'Transparent PNG insertion', 'Size, color, and placement'],
    features: [
      { title: 'Designed for the Slides sidebar', text: 'A compact two-column browser keeps search, filters, selection, and styling readable inside Google\'s fixed 300 px Editor add-on pane.' },
      { title: 'Slide-ready styling', text: 'Choose a point size, exact hex color, quick swatch, and center, corner, or content placement before insertion.' },
      { title: 'Sanitized transparent output', text: 'Remote SVG is cleaned in the browser and rendered to a transparent high-resolution PNG that Google Slides accepts natively.' },
      { title: 'Minimal presentation access', text: 'The add-on uses only current-presentation and container-UI scopes, sends no document content to IconSearch, and embeds no secret keys.' },
    ],
    workflow: ['Build and push the clasp-ready Apps Script files', 'Create an Editor add-on test deployment for Google Slides', 'Search and style an icon in the sidebar', 'Insert the selected PNG onto the current slide'],
    requirements: ['Node.js 22.13 or newer', 'A Google account with Apps Script access', 'A Google Slides presentation for the test deployment'],
    setup: 'cd google-slides-addon\nnpm install\nnpm run verify\nnpm run login\nnpm run push',
    releaseTitle: 'Ready for an Apps Script Editor add-on test deployment.',
    releaseText: 'The 300 px sidebar, sanitizer, PNG conversion, bounded Apps Script insertion path, least-privilege manifest, clasp build, tests, and secret checks pass locally. A standard Cloud project, real Slides host QA, OAuth consent configuration, listing assets, and Google Workspace Marketplace review remain before public availability.',
  },
  'raycast-extension': {
    slug: 'raycast-extension',
    name: 'Raycast Extension',
    platform: 'Raycast',
    icon: 'command',
    mark: 'RA',
    status: 'Package ready',
    statusTone: 'ready',
    eyebrow: 'FAST DESKTOP SEARCH',
    title: 'Find the right icon without leaving Raycast.',
    description: 'Search the live IconSearch catalog, inspect a clean preview, and copy or paste production-ready icon output into the app in front.',
    accent: '#f43f5e',
    accentMuted: 'rgba(244, 63, 94, 0.16)',
    previewContext: 'Search Icons - Raycast',
    previewAction: 'Copy React',
    outputLabel: 'React output',
    output: '<House className="h-5 w-5" />',
    account: 'Free account',
    dragAndDrop: false,
    capabilities: ['Recents and favorites', 'Library and style filters', 'Six output formats'],
    features: [
      { title: 'Raycast-native search', text: 'A compact list and detail workflow keeps keyboard navigation fast and previews readable.' },
      { title: 'Copy or paste output', text: 'Send React, SVG, Vue, Svelte, Tailwind, URL, or an SVG file to the active app.' },
      { title: 'Focused filters', text: 'Narrow results by library, Iconify collection, style, and commercial-safety status.' },
      { title: 'Secure connection', text: 'Browser approval stores only a revocable IconSearch product token in Raycast.' },
    ],
    workflow: ['Open Search Icons in Raycast', 'Connect a free IconSearch account', 'Search and filter the live catalog', 'Copy or paste the selected output'],
    requirements: ['Raycast desktop app on macOS or Windows', 'Node.js 22.14 or newer and npm 7 or newer for development', 'Free IconSearch account for live search'],
    setup: 'cd raycast-extension\nnpm install\nnpm run dev',
    releaseTitle: 'Prepared for Raycast Store review.',
    releaseText: 'The distribution build, manifest, 512 px icon, Store screenshots, changelog, ESLint, Prettier, and TypeScript checks pass. A final signed-in host test and npm run publish from the iconsearch Raycast account remain before Store review.',
  },
  'tailwind-plugin': {
    slug: 'tailwind-plugin',
    name: 'Tailwind Plugin',
    platform: 'Tailwind CSS',
    icon: 'wind',
    mark: 'TW',
    status: 'Package ready',
    statusTone: 'ready',
    eyebrow: 'UTILITY-FIRST ICONS',
    title: 'Use open-source icons as Tailwind utilities.',
    description: 'Add icons with a single class, then control their size and color with the same Tailwind utilities already used across your interface.',
    accent: '#22d3ee',
    accentMuted: 'rgba(34, 211, 238, 0.15)',
    previewContext: 'component.tsx - Tailwind CSS',
    previewAction: 'Copy class',
    outputLabel: 'Utility markup',
    output: '<span class="is-icon-[lucide--home] text-2xl text-cyan-500"></span>',
    account: 'Free IconSearch account',
    dragAndDrop: false,
    capabilities: ['Secure browser sign-in', 'Tailwind 3.4 and 4', 'currentColor styling', 'Iconify-compatible names'],
    features: [
      { title: 'Native utility workflow', text: 'Use dynamic icon selectors beside familiar text color and font-size utilities.' },
      { title: 'One IconSearch account', text: 'Connect through the browser once, then use the same free account and entitlement system as every IconSearch integration.' },
      { title: 'Tailwind 3 and 4', text: 'Configure the package from JavaScript or load it with the Tailwind 4 CSS plugin directive.' },
      { title: 'Broad icon coverage', text: 'Reference Iconify-compatible collection and icon names without shipping a local SVG bundle.' },
    ],
    workflow: ['Install the package as a dev dependency', 'Connect or create a free IconSearch account', 'Register the plugin in CSS or config', 'Style an icon with Tailwind size and color utilities'],
    requirements: ['Node.js 18.18 or newer', 'Tailwind CSS 3.4 or newer', 'Free IconSearch account'],
    setup: 'npm install -D @iconsearch/tailwind\nnpx @iconsearch/tailwind login\nnpx @iconsearch/tailwind whoami',
    releaseTitle: 'Account-gated package ready for final verification.',
    releaseText: 'Browser sign-in, revocable Tailwind sessions, Tailwind 3.4 and 4 compilation tests, and the dry package inspection are included. Apply the Tailwind product migration and deploy the website before the first public npm release.',
  },
  'mcp-server': {
    slug: 'mcp-server',
    name: 'MCP Server',
    platform: 'MCP clients',
    icon: 'radio',
    mark: 'MC',
    status: 'Local build',
    statusTone: 'local',
    eyebrow: 'ICONS FOR AI WORKFLOWS',
    title: 'Give AI tools a reliable icon search.',
    description: 'Connect IconSearch to MCP-compatible clients so agents can search the live catalog and return exact React, SVG, Vue, Svelte, Tailwind, or URL output.',
    accent: '#34d399',
    accentMuted: 'rgba(52, 211, 153, 0.14)',
    previewContext: 'iconsearch_search - MCP client',
    previewAction: 'Return snippet',
    outputLabel: 'Tool result',
    output: '{ "icon": "lucide:house", "format": "react" }',
    account: 'Free account',
    dragAndDrop: false,
    capabilities: ['Five focused MCP tools', 'Local token storage', 'stdio transport'],
    features: [
      { title: 'Search as a tool call', text: 'Agents can query the current IconSearch catalog instead of guessing package names or icon exports.' },
      { title: 'Exact code output', text: 'Generate React, SVG, Vue, Svelte, Tailwind, or URL snippets for a selected result.' },
      { title: 'Protocol-safe logging', text: 'Protocol data stays on stdout while diagnostics are written separately to stderr.' },
      { title: 'Revocable sign-in', text: 'Device sign-in stores the product token in the local user configuration directory.' },
    ],
    workflow: ['Build and start the local server', 'Add the stdio command to an MCP client', 'Complete browser device sign-in once', 'Ask the client to search and generate an icon snippet'],
    requirements: ['Node.js 18 or newer', 'An MCP-compatible desktop or editor client', 'Free IconSearch account for authenticated tools'],
    setup: 'cd mcp-server\nnpm install\nnpm run build\nnpm run start',
    releaseTitle: 'Built for local MCP client testing.',
    releaseText: 'The TypeScript server builds successfully and exposes sign-in, status, search, and snippet tools. Packaging and public distribution are still pending.',
  },
  'jetbrains-plugin': {
    slug: 'jetbrains-plugin',
    name: 'JetBrains Plugin',
    platform: 'JetBrains IDEs',
    icon: 'blocks',
    mark: 'JB',
    status: 'Development build',
    statusTone: 'development',
    eyebrow: 'EDITOR TOOL WINDOW',
    title: 'Search and insert icons inside JetBrains IDEs.',
    description: 'Keep icon discovery beside your code with a focused tool window, fast text-first results, and snippets for the frontend format you are editing.',
    accent: '#fb7185',
    accentMuted: 'rgba(251, 113, 133, 0.15)',
    previewContext: 'IconSearch - IntelliJ IDEA',
    previewAction: 'Insert at caret',
    outputLabel: 'Editor output',
    output: '<Icon icon="lucide:house" className="h-5 w-5" />',
    account: 'Free account',
    dragAndDrop: false,
    capabilities: ['Tool window workflow', 'Password Safe token', 'Copy or insert'],
    features: [
      { title: 'Native tool window', text: 'Open IconSearch from View > Tool Windows and keep it beside the active editor.' },
      { title: 'Fast result navigation', text: 'A text-first list avoids heavy previews while scrolling through broad search results.' },
      { title: 'Insert at the caret', text: 'Copy a snippet or place it directly into the current editor selection.' },
      { title: 'IDE-safe credentials', text: 'The revocable product token is stored with JetBrains Password Safe.' },
    ],
    workflow: ['Start the IntelliJ development IDE', 'Open the IconSearch tool window', 'Approve browser sign-in', 'Search and insert the selected snippet'],
    requirements: ['Gradle 9 or newer', 'Java 17 or newer', 'A compatible JetBrains IDE'],
    setup: 'cd jetbrains-plugin\ngradle runIde',
    releaseTitle: 'Source ready for a full Gradle verification.',
    releaseText: 'The plugin workflow and backend product are implemented. A Gradle wrapper, full runIde test, signing, and JetBrains Marketplace review remain.',
  },
  'storybook-addon': {
    slug: 'storybook-addon',
    name: 'Storybook Addon',
    platform: 'Storybook',
    icon: 'book',
    mark: 'SB',
    status: 'Package ready',
    statusTone: 'ready',
    eyebrow: 'COMPONENT WORKBENCH',
    title: 'Choose icons beside the components that use them.',
    description: 'Search IconSearch from a Storybook panel and copy production-ready snippets without breaking the component development loop.',
    accent: '#ff4785',
    accentMuted: 'rgba(255, 71, 133, 0.15)',
    previewContext: 'Button.stories.tsx - Storybook',
    previewAction: 'Copy snippet',
    outputLabel: 'React snippet',
    output: '<Icon icon="lucide:arrow-right" aria-hidden />',
    account: 'Free account',
    dragAndDrop: false,
    capabilities: ['Storybook panel', 'Framework-neutral search', 'Six output formats'],
    features: [
      { title: 'Panel-based search', text: 'Browse icons in the same workspace used to inspect stories, controls, and component states.' },
      { title: 'Framework-friendly output', text: 'Copy React, SVG, Tailwind, Vue, Svelte, or URL output from one addon.' },
      { title: 'Useful catalog filters', text: 'Choose a library, commercial-safety state, and desired snippet format.' },
      { title: 'Shared product vocabulary', text: 'Design-system contributors can discuss the same icon names while reviewing components.' },
    ],
    workflow: ['Build or link the addon package', 'Add it to .storybook/main.ts', 'Open the IconSearch panel', 'Search and copy a snippet into the component'],
    requirements: ['Storybook 9 or newer', 'React 18 or newer in the host project', 'Node.js and npm for local linking'],
    setup: 'cd storybook-addon\nnpm install\nnpm run build\nnpm run typecheck',
    releaseTitle: 'Package output is ready for a host-app test.',
    releaseText: 'Build and typecheck pass locally. The next steps are an end-to-end linked Storybook test and publication to the Storybook addon ecosystem.',
  },
  'canva-app': {
    slug: 'canva-app',
    name: 'Canva App',
    platform: 'Canva',
    icon: 'image',
    mark: 'CA',
    status: 'Development preview',
    statusTone: 'development',
    eyebrow: 'DESIGN-SIDE SEARCH',
    title: 'Insert clean SVG icons into Canva designs.',
    description: 'Search and filter the live catalog in a Canva side panel, then upload the selected SVG as a design asset and place it on the current page.',
    accent: '#7d2ae8',
    accentMuted: 'rgba(125, 42, 232, 0.16)',
    previewContext: 'IconSearch - Canva Apps',
    previewAction: 'Add to design',
    outputLabel: 'Selected asset',
    output: 'lucide:house - SVG asset - 96 px',
    account: 'Free account',
    dragAndDrop: false,
    capabilities: ['Canva side panel', 'SVG asset upload', 'Insert into design'],
    features: [
      { title: 'Clear panel search', text: 'Visible icon cards, library filtering, and commercial-safety controls keep browsing focused.' },
      { title: 'SVG asset insertion', text: 'Upload the selected icon with an explicit non-AI disclosure and insert it into the design.' },
      { title: 'Live catalog access', text: 'Search current IconSearch results without embedding a large icon bundle in the app.' },
      { title: 'Secure product sign-in', text: 'Canva receives a revocable app token after account approval in the browser.' },
    ],
    workflow: ['Start the local Canva app bundle', 'Set the development URL in Canva', 'Open the app in a test design', 'Search and add the selected SVG asset'],
    requirements: ['Node.js 22 or 24', 'A Canva Developer Portal app', 'A Canva test design for previewing'],
    setup: 'cd canva-app\nnpm install\nnpm start\n# Development URL: http://localhost:8080/app.js',
    releaseTitle: 'Ready for Canva Developer Portal preview.',
    releaseText: 'The app builds and typechecks locally. It still needs a complete in-Canva interaction test, listing assets, and Canva review before public availability.',
  },
  'wordpress-plugin': {
    slug: 'wordpress-plugin',
    name: 'WordPress Plugin',
    platform: 'WordPress',
    icon: 'panel',
    mark: 'WP',
    status: 'Development build',
    statusTone: 'development',
    eyebrow: 'GUTENBERG SIDEBAR',
    title: 'Drop styled icons into WordPress content.',
    description: 'A native Gutenberg sidebar for finding an icon, adjusting its size and color, and inserting it into a post by click or drag.',
    accent: '#38bdf8',
    accentMuted: 'rgba(56, 189, 248, 0.15)',
    previewContext: 'Page editor - WordPress',
    previewAction: 'Insert selected',
    outputLabel: 'Block output',
    output: 'core/html - 96 px - current color',
    account: 'No account',
    dragAndDrop: true,
    capabilities: ['Gutenberg sidebar', 'Size and color controls', 'Click or drag insertion'],
    features: [
      { title: 'Native editor sidebar', text: 'Open IconSearch from the Gutenberg toolbar without leaving the post or page.' },
      { title: 'Readable previews', text: 'A large selected preview and compact two-column result grid keep icon shapes visible.' },
      { title: 'Style before insertion', text: 'Set size, choose a color, or use a quick swatch before creating the block.' },
      { title: 'Click or drag', text: 'Insert the selected icon as a core HTML block or drag a result into the editor canvas.' },
    ],
    workflow: ['Install the folder in wp-content/plugins', 'Activate IconSearch in WordPress Admin', 'Open the Gutenberg sidebar', 'Style and insert or drag an icon into the page'],
    requirements: ['A local WordPress installation', 'The Gutenberg block editor', 'Network access to the public IconSearch API'],
    setup: 'Copy wordpress-plugin to:\nwp-content/plugins/iconsearch\n\nActivate IconSearch, then open the block editor.',
    releaseTitle: 'Built for local Gutenberg testing.',
    releaseText: 'The editor UI and insertion flow are implemented without accounts or private keys. Cross-version WordPress testing, packaging, and directory review remain.',
  },
  'shopify-extension': {
    slug: 'shopify-extension',
    name: 'Shopify Extension',
    platform: 'Shopify',
    icon: 'shop',
    mark: 'SH',
    status: 'Development build',
    statusTone: 'development',
    eyebrow: 'THEME APP EXTENSION',
    title: 'Build flexible icon rows in Shopify themes.',
    description: 'Search, style, drag, and reorder icons in a theme-editor helper, then save a transparent list of icon IDs to a storefront app block.',
    accent: '#5fd25f',
    accentMuted: 'rgba(95, 210, 95, 0.14)',
    previewContext: 'Theme editor - Shopify',
    previewAction: 'Copy selected IDs',
    outputLabel: 'Block setting',
    output: 'lucide:truck, lucide:shield-check, lucide:refresh-cw',
    account: 'No IconSearch account',
    dragAndDrop: true,
    capabilities: ['Theme app block', 'Draggable selected tray', 'Merchant style controls'],
    features: [
      { title: 'Theme editor helper', text: 'Search and preview icons beside the app block settings used by a merchant.' },
      { title: 'Drag and reorder', text: 'Build a selected tray, change item order, and review the complete storefront icon row.' },
      { title: 'Merchant-owned styling', text: 'Control icon size, color, gap, alignment, labels, and heading from theme settings.' },
      { title: 'Review-safe persistence', text: 'Copy the chosen icon IDs into the Shopify-owned block field instead of silently changing settings.' },
    ],
    workflow: ['Place the extension in a Shopify app workspace', 'Run the app in development mode', 'Add the Icon row block in a test theme', 'Choose and reorder icons, then save their IDs'],
    requirements: ['A Shopify Partner development store', 'A parent Shopify app workspace', 'Shopify CLI for app development'],
    setup: 'Place shopify-extension under:\nextensions/iconsearch-theme\n\nThen run:\nshopify app dev',
    releaseTitle: 'Theme extension structure is ready for app testing.',
    releaseText: 'The custom checker passes. The extension still needs a parent Shopify app, development-store verification, and deployment through Shopify CLI.',
  },
  'adobe-plugin': {
    slug: 'adobe-plugin',
    name: 'Adobe Express Add-on',
    platform: 'Adobe Express',
    icon: 'brush',
    mark: 'AE',
    status: 'Development preview',
    statusTone: 'development',
    eyebrow: 'EXPRESS ADD-ON',
    title: 'Search, style, and drag icons into Adobe Express.',
    description: 'A clear add-on panel with large previews, precise size and color controls, and both click and drag insertion for the current document.',
    accent: '#ff3366',
    accentMuted: 'rgba(255, 51, 102, 0.15)',
    previewContext: 'IconSearch - Adobe Express',
    previewAction: 'Insert on canvas',
    outputLabel: 'Canvas asset',
    output: 'lucide:house - SVG - 96 px - #111827',
    account: 'No account',
    dragAndDrop: true,
    capabilities: ['Large SVG preview', 'Size and color controls', 'Click or drag insertion'],
    features: [
      { title: 'Visual search panel', text: 'Search, library, style, and commercial-safety filters stay visible above clear result cards.' },
      { title: 'Precise styling', text: 'Adjust icon size, use a color picker, or choose a fast preset swatch before insertion.' },
      { title: 'Two insertion paths', text: 'Add the selected SVG with a button or drag the result directly onto the Express document.' },
      { title: 'Public endpoints only', text: 'The add-on contains no private tokens or embedded service keys and uses the public icon API.' },
    ],
    workflow: ['Start the Adobe add-on development server', 'Load it in Adobe Express development mode', 'Search and style an icon', 'Click Insert or drag the result onto the canvas'],
    requirements: ['Adobe Express add-on development access', 'Node.js and npm for the local CLI flow', 'A test Express document'],
    setup: 'cd adobe-plugin\nnpm run check\nnpm run start',
    releaseTitle: 'Ready for an Adobe Express development test.',
    releaseText: 'Static checks pass and no confidential keys are included. The add-on still needs a full Express SDK test, package validation, and distribution review.',
  },
  'obsidian-plugin': {
    slug: 'obsidian-plugin',
    name: 'Obsidian Plugin',
    platform: 'Obsidian',
    icon: 'gem',
    mark: 'OB',
    status: 'Development build',
    statusTone: 'development',
    eyebrow: 'PORTABLE NOTE ASSETS',
    title: 'Place styled SVG icons into Obsidian notes.',
    description: 'Search from an Obsidian sidebar, adjust size and color, then save a sanitized SVG into the vault and insert a portable wiki embed.',
    accent: '#a78bfa',
    accentMuted: 'rgba(167, 139, 250, 0.16)',
    previewContext: 'IconSearch - Obsidian',
    previewAction: 'Insert into note',
    outputLabel: 'Markdown embed',
    output: '![[IconSearch Icons/lucide-house-111827-96.svg|96]]',
    account: 'No account',
    dragAndDrop: true,
    capabilities: ['Vault-local SVG files', 'Size and color controls', 'Click or drag insertion'],
    features: [
      { title: 'Sidebar and command access', text: 'Open IconSearch from the ribbon or command palette while keeping the current note visible.' },
      { title: 'Portable vault assets', text: 'Sanitized SVG files live inside the vault, so notes do not depend on a remote image URL.' },
      { title: 'Flexible insertion', text: 'Use the Insert action, double-click a result, or drag a card into an active Markdown note.' },
      { title: 'Configurable defaults', text: 'Choose the icon folder, default size, color, legal-safe state, and API endpoint in settings.' },
    ],
    workflow: ['Copy the plugin files into a development vault', 'Enable IconSearch under Community plugins', 'Open the sidebar and choose an icon', 'Style it and insert or drag it into the note'],
    requirements: ['Obsidian desktop', 'A separate development vault for testing', 'Community plugins enabled in that vault'],
    setup: 'Copy manifest.json, main.js, and styles.css to:\n.obsidian/plugins/iconsearch\n\nReload Obsidian and enable IconSearch.',
    releaseTitle: 'Ready for an isolated Obsidian vault test.',
    releaseText: 'The plugin checker and JavaScript syntax check pass. Community publication still needs repository setup, a matching GitHub release, and Obsidian review.',
  },
}

export function createIntegrationMetadata(config: IntegrationConfig): Metadata {
  const iconCount = SEARCHABLE_ICON_COUNT.toLocaleString('en-US')
  const description = `${config.description} Explore ${iconCount} searchable icons with IconSearch for ${config.platform}.`

  return {
    title: `IconSearch ${config.name} - ${config.status}`,
    description,
    alternates: { canonical: `/${config.slug}` },
    openGraph: {
      title: `IconSearch ${config.name}`,
      description,
      url: `/${config.slug}`,
      type: 'website',
    },
  }
}
